const ru = {
  january: "Январь",
  february: "Февраль",
  march: "Март",
  april: "Апрель",
  maylong: "Май",
  june: "Июнь",
  july: "Июль",
  august: "Август",
  september: "Сентябрь",
  october: "Октябрь",
  november: "Ноябрь",
  december: "Декабрь",
  jan: "01",
  feb: "02",
  mar: "03",
  apr: "04",
  may: "05",
  jun: "06",
  jul: "07",
  aug: "08",
  sep: "09",
  oct: "10",
  nov: "11",
  dec: "12",
  sunday: "Воскресенье",
  monday: "Понедельник",
  tuesday: "Вторник",
  wednesday: "Среда",
  thursday: "Четверг",
  friday: "Пятница",
  saturday: "Суббота",
  sun: "	Вс",
  mon: "	Пн",
  tue: "	Вт",
  wed: "	Ср",
  thu: "	Чт",
  fri: "	Пт",
  sat: "	Сб",
  res: "Ответств.",
  dur: "Длит.",
  comp: "% выполнения",
  completion: "Выполнено",
  startdate: "Нач. дата",
  planstartdate: "Plan Нач. дата",
  enddate: "Кон. дата",
  planenddate: "Прогноз",
  cost: "Cost",
  moreinfo: "Детали",
  nodata: "Нет данных",
  notes: "Дополнительно",
  format: "Формат",
  hour: "Час",
  day: "День",
  week: "Неделя",
  month: "Месяц",
  quarter: "Квартал",
  hours: "Часов",
  days: "Дней",
  weeks: "Недель",
  months: "Месяцев",
  quarters: "Кварталов",
  hr: "ч.",
  dy: "дн.",
  wk: "нед.",
  mth: "мес.",
  qtr: "кв.",
  hrs: "ч.",
  dys: "дн.",
  wks: "нед.",
  mths: "мес.",
  qtrs: "кв.",
  tooltipLoading: "Загрузка...",
};

export { ru };
